(function(){
  const $=id=>document.getElementById(id),esc=ZP.esc;let validation='미검증',detailSummary='미검증',last=null;
  try{last=JSON.parse(sessionStorage.getItem('zp_last_diag')||'null');}catch(_){}
  const row=(k,v)=>`<tr><th scope="row">${esc(k)}</th><td>${esc(v??'—')}</td></tr>`;
  function render(){const d=ZP.diag;$('t').innerHTML=row('현재 화면 데이터',ZP.isDemo()?'시연 예시':'비짓서울 API')+row('조사한 서울 장소',window.ZPDescriptions?ZPDescriptions.count()+'곳 · 공식 사진·사전 생성 AI 설명':'미로드')+row('Google 지도 진단',d.map?(d.map.status+' · '+(d.map.code||d.map.message)):'지도 화면에서 확인')+row('프록시 주소',ZP.config.VISITSEOUL_PROXY_URL||'미설정')+row('설정 확인',ZP.config.DATA_SOURCE==='visitseoul'&&ZP.config.VISITSEOUL_PROXY_URL?'설정됨 · 실제 연결은 별도 검증':'설정 확인 필요')+row('목록·상세 연결 검증',validation)+row('상세 정보 상태',detailSummary)+row('마지막 API 호출',d.lastCall)+row('프록시 캐시 시각',d.cacheAt)+row('이전 검색 성공 / 실패',last?`${last.normalized||0} / ${last.failed||0}`:'이전 검색 기록 없음')+row('이전 검색 추천 수',last?.passed??'—')+row('이전 검색 확인 시각',last?.savedAt||'—');$('demoOn').hidden=!ZP.config.ALLOW_DEMO;}
  $('ping').onclick=async()=>{$('ping').disabled=true;validation='확인 중';detailSummary='확인 중';$('out').textContent='목록과 상세 정보를 조회하고 있습니다…';render();
    try{const r=await ZP.adapters.visitseoul.list({com_ctgry_sn:'Cg1x6l1',lang_code_id:'ko',page_no:1});if(r.result_code!==undefined&&Number(r.result_code)!==200)throw new Error('목록 API가 오류를 반환했습니다.');const items=ZP.findItems(r);if(!Array.isArray(items)||!items.length)throw new Error('검증에 사용할 목록 항목이 없습니다.');const id=items[0].cid??ZP.dig(items[0],'cid');if(!id)throw new Error('목록에 장소 식별자가 없습니다.');const info=await ZP.adapters.visitseoul.info(id);if(info.result_code!==undefined&&Number(info.result_code)!==200)throw new Error('상세 API가 오류를 반환했습니다.');const p=ZP.normalize(info);if(p.id!==String(id))throw new Error('목록과 상세의 장소 식별자가 다릅니다.');validation='목록·상세 연결 확인';detailSummary=`${p.name} · 운영시간 ${p.hours.confidence==='high'?'해석 가능':'확인 필요'} / 휴무일 ${p.closed.confidence==='high'?'해석 가능':'확인 필요'}`;$('out').textContent=`목록 ${items.length}건 수신\n상세 1건 정규화 확인\n콘텐츠 ID: ${p.id}\n연결 성공은 모든 장소의 방문 가능 판정을 의미하지 않습니다.`;ZP.diag.lastError=null;
    }catch(e){validation='검증 실패';detailSummary='다시 확인 필요';$('out').textContent=e.message||'연결에 실패했습니다.';ZP.diag.lastError=e.message;}finally{$('ping').disabled=false;render();}}
  $('demoOn').onclick=()=>{ZP.enableDemo();$('out').textContent='시연 예시를 선택했습니다. 처음으로 돌아가 조건을 고르세요. 실제 API 조회 결과와 구분해 표시합니다.';render();};
  $('demoOff').onclick=()=>{ZP.disableDemo();$('out').textContent='실제 비짓서울 데이터를 사용합니다.';render();};render();
})();
