(async function(){
  const $=id=>document.getElementById(id),U=ZPUI,esc=U.esc,S=ZP.loadState();
  if(!S?.origin){location.replace('index.html');return;}
  let last=null,filter='70',busy=false,generation=0,controller=null,map=null,mapPromise=null,shown=[],lastPaintAt=0,target=50;
  const sel=$('sort');Object.entries(ZP.sortLabels).forEach(([value,label])=>sel.add(new Option(label,value)));sel.value=ZP.defaultSort(S);if(!sel.value)sel.value='near';
  $('cond').innerHTML=U.conditions(S).map(t=>`<span class="chip">${esc(t)}</span>`).join('');$('mapbox').hidden=matchMedia('(max-width:1000px)').matches;
  function mapError(message){$('maperr').hidden=false;const d=ZP.diag.map;$('maperr').textContent=(message||'Google 지도를 불러오지 못했습니다. 목록은 계속 이용할 수 있습니다.')+(d?.code?' '+d.code+' · '+d.message:'');$('mapretry').hidden=false;$('mapprov').textContent='Google 지도 확인 필요';}
  async function ensureMap(){if(map)return map;if(mapPromise)return mapPromise;mapPromise=Promise.resolve().then(()=>ZP.map($('map'),S.origin,14,mapError)).then(m=>{map=m;if(m){$('mapprov').textContent=m.provider==='google'?'구글 지도':'오픈스트리트맵';paintMap();}else mapError();return m;}).catch(()=>{mapError();return null;});return mapPromise;}
  $('mapretry').onclick=async()=>{map?.destroy?.();map=null;mapPromise=null;$('maperr').hidden=true;$('mapretry').hidden=true;await ensureMap();};
  function paintMap(){if(!map)return;try{map.clear();map.add(S.origin,{me:true,label:S.originLabel||'출발지'});shown.forEach((x,i)=>map.add(x.p,{num:i+1,label:`${i+1}. ${x.p.name}`,popup:`<div class="pop"><b>${esc(x.p.name)}</b><span>${esc(U.scoreText(x))}</span><a href="place.html?id=${encodeURIComponent(x.p.id)}">상세 보기</a></div>`}));map.fit();map.resize?.();}catch(_){mapError();}}
  function highlight(p,on){if(map)map.focus(p,on);}
  $('maptoggle').onclick=async()=>{const box=$('mapbox');box.hidden=!box.hidden;$('maptoggle').setAttribute('aria-expanded',String(!box.hidden));$('maptoggle').textContent=box.hidden?'지도 보기':'지도 닫기';if(!box.hidden){await ensureMap();map?.resize?.();box.scrollIntoView({block:'nearest',behavior:'auto'});}};
  function section(id,title,items,offset=0){$(id+'Section').hidden=!items.length;$(id+'Title').textContent=title+' '+items.length+'곳';const container=id==='complete'?'cards':id==='partial'?'partialcards':'checkcards';$(container).replaceChildren(...items.map((x,i)=>U.card(x,id==='check'?null:offset+i+1,highlight)));}
  function render(result=last,interim=false){
    if(!result)return;const R=ZP.evaluate(result.places||[],S,sel.value,{minScore:filter==='50'?50:70,completeOnly:filter==='complete'});
    shown=[...R.open,...R.partial];$('loading').hidden=true;$('cnt').textContent=`방문 조건을 확인한 추천 ${shown.length}곳`;const ctx=R.ctx;
    $('meta').textContent=`${ctx.originLabel} 출발 · ${ZP.fmtDate(ctx.date)} ${ZP.fmtH(ctx.hour)} · ${result.received??R.total}건 수신 / ${R.total}곳 확인${result.availableTotal?` · 분류별 전체 ${result.availableTotal}건${result.availableTotalIsCategorySum?" (분류 간 중복 가능)":""}`:' · 수집한 후보 기준'}${result.truncated?' · 아직 확인하지 않은 후보가 있습니다':''}`;
    $('scopeNotice').hidden=!result.scopeExpanded&&!result.targetMet;if(result.scopeExpanded)$('scopeNotice').textContent='선택 분야만으로 50곳을 확보하지 못해 다른 분야까지 조사했습니다. 관심사 일치 여부는 점수에 반영됩니다.';else if(result.targetMet)$('scopeNotice').textContent=`실제 상세 ${R.total}곳을 확인했습니다. 방문 가능한 추천 수는 조건에 따라 달라집니다.`;
    section('complete','조건 충족',R.open);section('partial','일부 조건이 다른 대안',R.partial,R.open.length);section('check','방문 전 확인 필요',R.check);
    const below=[...(R.below||[]),...(R.hiddenPartial||[])];$('belowSection').hidden=!below.length;$('belowTitle').textContent=`선호 기준 밖의 장소 ${below.length}곳 보기`;$('belowcards').replaceChildren(...below.map(x=>U.card(x,null)));$('excl').hidden=!R.shut.length;$('exclsum').textContent=`제외된 장소 ${R.shut.length}곳 · 이유 보기`;$('exclax').textContent=Object.entries(R.byAxis||{}).map(([axis,n])=>`${U.axisNames[axis]||axis} ${n}건`).join(' · ');$('shut').replaceChildren(...R.shut.map(x=>U.card(x,null)));
    const failed=result.failed||0;$('partialFailure').hidden=!failed;if(failed){$('partialFailure').innerHTML=`<span>${failed}건의 정보를 불러오지 못했습니다. 현재 결과는 확인에 성공한 장소만 포함합니다.</span><button id="retryFailed" ${busy?'disabled':''}>누락된 정보 다시 확인</button>`;$('retryFailed').onclick=()=>retryMissing();}
    $('empty').hidden=shown.length>0||interim;
    if(!shown.length&&!interim){let heading='현재 기준에 맞는 추천이 없습니다',body='시간이나 출발지를 바꾸면 새로운 방문 조건으로 다시 확인합니다.';if(failed){heading='일부 장소를 아직 확인하지 못했습니다';body='조회 실패가 있어 조건에 맞는 장소가 없다고 단정할 수 없습니다. 누락된 정보를 다시 확인해 주세요.';}else if(R.check.length||(R.hiddenCheck||[]).length){heading='방문 조건을 확정한 추천이 없습니다';body=R.check.length?`아래 ${R.check.length}곳은 운영·입장 조건을 확인하면 방문을 검토할 수 있습니다.`:`방문 조건 미확인 ${(R.hiddenCheck||[]).length}곳이 완전 충족 필터에서 숨겨졌습니다. 기본 추천에서 확인할 수 있습니다.`;}
      const relaxed=ZP.evaluate(result.places||[],S,sel.value,{minScore:50}),count=relaxed.open.length+relaxed.partial.length;
      $('empty').innerHTML=`<h3>${heading}</h3><p>${body}</p><div class="actions">${filter!=='50'&&count?`<button class="btn btn-main" id="relax">조건이 일부 다른 대안 ${count}곳 보기</button>`:''}<a class="btn btn-ghost" href="index.html">시간·출발지 수정</a></div>`;if($('relax'))$('relax').onclick=()=>setFilter('50');}
    $('demoBanner').hidden=!result.demo;$('src').textContent=`출처: ${result.source||'비짓서울 API'} · 조회 ${new Date(result.retrievedAt||Date.now()).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · 장소별 원문·갱신일은 상세에서 확인하세요.`;
    $('more').hidden=!result.truncated||target>=200;$('more').disabled=busy;if(!interim)paintMap();U.rememberDiag({received:result.received,normalized:R.total,failed,passed:shown.length});}
  function setFilter(value){filter=value;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===value)));render();}
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));sel.onchange=()=>render();$('demoOff').onclick=()=>{ZP.disableDemo();last=null;load();};$('more').onclick=()=>{target=Math.min(200,target+50);load();};
  async function retryMissing(){if(busy||!last)return;const ids=last.failedIds||[];if(!ids.length){$('status').textContent='목록 조회에 누락이 있습니다. 조건을 수정해 다시 검색할 수 있습니다.';return;}busy=true;const result=last,nextPlaces=[...result.places],failed=[];let next=0;const mine=++generation;controller?.abort();controller=new AbortController();$('results').setAttribute('aria-busy','true');render();try{await Promise.all(Array.from({length:Math.min(3,ids.length)},async()=>{while(next<ids.length){const id=ids[next++];try{const p=await ZP.getPlace(id,{retry:false,signal:controller.signal});if(!ZP.outsideSeoul(p)&&!nextPlaces.some(x=>x.id===id))nextPlaces.push(p);}catch(e){if(e.name==='AbortError')throw e;failed.push(id);}}}));if(mine!==generation)return;const listFailures=(result.failures||[]).filter(x=>x.kind==='list');last={...result,places:nextPlaces,failedIds:failed,failed:failed.length+listFailures.length,failures:[...listFailures,...(result.failures||[]).filter(x=>failed.includes(x.cid))],targetMet:nextPlaces.length>=target};$('status').textContent=`누락 정보 재확인 완료 · 상세 ${nextPlaces.length}곳 확인`;}catch(e){if(e.name!=='AbortError')$('status').textContent='누락 정보 재확인을 마치지 못했습니다.';}finally{if(mine===generation){busy=false;render();$('results').setAttribute('aria-busy','false');}}}
  function clearResults(){shown=[];['completeSection','partialSection','checkSection','belowSection','excl','empty','partialFailure','demoBanner','more'].forEach(id=>$(id).hidden=true);['cards','partialcards','checkcards','belowcards','shut'].forEach(id=>$(id).replaceChildren());$('meta').textContent='';$('src').textContent='';paintMap();}
  async function load(){const mine=++generation;controller?.abort();controller=new AbortController();busy=true;if(!last){clearResults();$('loading').hidden=false;$('cnt').textContent='방문 조건을 확인하고 있습니다';}$('results').setAttribute('aria-busy','true');$('err').hidden=true;$('status').textContent='운영정보를 확인하고 있습니다…';$('more').disabled=true;
    try{const r=await ZP.run(S,sel.value,message=>{if(mine===generation)$('status').textContent=message;},{target,signal:controller.signal,onPartial:part=>{if(mine===generation&&part?.places&&Date.now()-lastPaintAt>300){lastPaintAt=Date.now();render(part,true);}}});if(mine!==generation)return;last=r;busy=false;render();$('status').textContent='확인이 끝났습니다. 원하는 순서와 선호 기준으로 살펴보세요.';}
    catch(e){if(mine!==generation||e.name==='AbortError')return;if(last)render(last);else clearResults();$('loading').hidden=true;$('status').textContent='';$('cnt').textContent=last?'이전 조회 결과':'정보를 불러오지 못했습니다';$('err').hidden=false;$('err').innerHTML=`<div class="errbox"><h3>운영정보 조회를 완료하지 못했습니다</h3><p>${esc(e.message||'잠시 후 다시 시도해 주세요.')}</p><div class="actions"><button class="btn btn-main" id="retry">다시 시도</button>${ZP.config.ALLOW_DEMO?'<button class="btn btn-ghost" id="demoOn">시연 예시로 보기</button>':''}<a class="btn btn-ghost" href="diagnostics.html">연동 진단</a></div></div>`;$('retry').onclick=load;if($('demoOn'))$('demoOn').onclick=()=>{ZP.enableDemo();last=null;load();};ZP.diag.lastError=e.message;U.rememberDiag();}
    finally{if(mine===generation){busy=false;$('results').setAttribute('aria-busy','false');$('more').disabled=false;}}}
  load();if(!$('mapbox').hidden)ensureMap();
})();
